Step2 리뷰요청드립니다.
gw-study/java-racingcar pull request #11
Opened 2021-06-05 04:34 UTC by AyoungLim1103

Step2 2단계 리뷰요청드립니다.

2021-06-05 21:53 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +public class Calculator {
프로덕션 코드 잘 만들어 주셨습니다👍
다만 프로덕션 코드의 위치는 test 패키지의 하위가 아닌 main 하위에 위치해 주세요.
test에 있는 코드는 배포시 제외가 되거든요😱

2021-06-05 21:56 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +        for(int i = 0; i < str.length - 2; i += 2) {
반복 패턴을 잘 찾으셨습니다👍

2021-06-05 22:33 UTC, gw-study requested changes
주말에도 열씨미 과정 진행해주셨네요👍🔥

프로덕션 코드(클래스 파일 위치는 조정 부탁드려요)와 테스트 코드를 잘 작성하시고
사칙연산 별 메소드도 잘 분리해주셨습니다.👌✔

몇가지 피드백 남겨놓았으니 확인 부탁드리겠습니다.🙇‍♂️

피드백이랑 같이 아래 내용도 확인 부탁드릴께요😂

 - PR브랜치 확인 부탁드릴께요.
 > ![image](https://user-images.githubusercontent.com/84048349/120906118-cc97f380-c691-11eb-8f56-8ac89b180b82.png)

수정하실 때 새로운 PR따지 말고 Edit 기능을 사용하시면 됩니다.

 > ![image](https://user-images.githubusercontent.com/84048349/120906160-11bc2580-c692-11eb-882b-df5b3dad2f38.png)

그럼 리뷰요청 기다리겠습니다.
편안한 주말보내세요~😄

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +            return add(firstNum, secondNum);
early return 패턴을 잘 활용하셨네요👏👏👏
아마 다음 step에서 나올거 같은데요, [자바 코드 컨벤션](https://naver.github.io/hackday-conventions-java/)도
미리 확인해 보시면 좋겠어요.(5.4. 조건/반복문에 중괄호 필수 사용 참조)

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +        for(int i = 0; i < str.length - 2; i += 2) {
반복 패턴을 잘 찾으셨습니다👍

한가지 Tip을 드리면 조건문을 함수로 만들면
코드가 명확해지고 읽기가 쉬워져요.
아래는 예시 참고하셔서 변경해 보시면 좋겠습니다😄
```suggestion
        for(isOperatiorPosition(index)) {
```

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +public class Calculator {
프로덕션 코드 잘 만들어 주셨습니다👍
다만 프로덕션 코드의 위치는 test 패키지의 하위가 아닌 main 하위에 위치해 주세요.
test에 있는 코드는 배포시 제외가 되거든요😱
(이 문자열 계산기 기능을 API로 제공할 수도 있으니까요ㅎ)

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/CalculatorTest.java
> +        });
```suggestion
        assertThatThrownBy(() -> calculator.getResult(" "))
                .isInstanceOf(IllegalArgumentException.class);
```
전 개인적으로 요렇게 사용하는게 조금 더 심플한 거 같더라구요😄

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/CalculatorTest.java
> +    @Test()
`Test`의 오타인거 같습니다.
아니면 다른 의도가 있는걸까요?🤔

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +    public int calculate(int firstNum, int secondNum, char operator){
이번 단계 핵심 메소드인데 잘 구현해주셨습니다👍

저도 처음에는 이렇게 사칙연산자 별로 if문을 사용해여 분기를 했더랬어요🤣
근데 코드가 더 깔끔해질 수 있는 방법이 있답니다.
아래 힌트 참고해 보셔서 고민 부탁드릴께요.
 - 힌트 : 반복되는 if문을 제거할 방법을 찾다보면 자바의 다형성을 생각하게 되는데요,
 다형성 구현에도 많은 방법이 있겠지만 이번 step에서는 enum 사용을 고민해 주세요. (enum 에도 스테틱이 아닌 맴버 필드와 메소드를 정의할 수 있어요.)

2021-06-05 22:33 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +        return false;
```suggestion
        return input.equals(" ") || input == null;
```
이렇게 변경할 수 있겠네요😄

2021-06-07 23:46 UTC, gw-study commented on src/test/java/calculator/Calculator.java
> +        for(int i = 0; i < str.length - 2; i += 2) {
제가 가이드를 잘못드렸습니다.😭
저 내용은 if문에 대한 조건을 함수로 만드는 내용인데 for문에는 적용하기 힘들어요.
참고만 해주시고 코드는 기존대로 하셔도 괜찮을거 같네요😅

2021-06-09 02:08 UTC, gw-study requested changes
안녕하세요. 피드백이 늦어져서 죄송해요😭
제가 리뷰요청을 늦게 확인했습니다. ㅜ

피드백 적용 잘해주셨습니다.
그리고 enum을 사용해서 사칙연산에 대한 코드도 잘 짜주셨어요👍
메소드명, 변수명도 적절하게 명명해 주셔서
코드 읽기가 수월했습니다.

이렇게 머지할수도 있을거 같은데요,
코드 중복에 대한 내용이 있어서 한번 더 Request Change할께요.
아래 내용 확인하시고 다시 요청 주시면 머지 가능할 거 같습니다.
> `Calculator`클래스의
`add` `subtract` `multiply` `divide`메소드의 역할은
이미 `Operator`에서 수행하고 있기 때문에 필요가 없는 코드인거 같네요😄
사칙연산 테스트도 마찬가지로 `calculate` 메소드만 사용하셔도 무방할거 같아요.

그럼 다시한번 리뷰 요청 부탁드릴께요🙇‍♂️

2021-06-09 02:08 UTC, gw-study commented on src/main/java/calculator/Calculator.java
> +        return input.equals(" ") || input == null;
피드백 적용👍

2021-06-09 02:08 UTC, gw-study commented on src/main/java/calculator/Calculator.java
> +import java.util.Map;
사용하지 않는 코드는 삭제해 주세요.

reformat 을 자주 놓친다 생각되시면 자동화 해 볼 수 있습니다.
인텔리제이를 사용하신 다면 `Save Actions`을 검색해보시고 사용해보세요.👍

2021-06-09 02:08 UTC, gw-study commented on src/main/java/calculator/Calculator.java
> +    public int calculate(int firstNum, int secondNum, String operator){
if문이 없어지고 훨씬 깔끔해졌군요!👏👏👏

한가지 바램이 있다면
메소드 위치를 호출하는 곳 다음으로 이동하면 좋겠습니다.

코드는 신문이나 글과 같아서 위에서부터 아래로 쭉 읽히는게 좋습니다😄

2021-06-09 02:08 UTC, gw-study commented on src/main/java/calculator/Operator.java
> +public enum Operator {
enum활용 아주 잘하셨어요👍
메소드명, 변수명도 적절하게 잘 작성해 주셨습니다👏

2021-06-09 02:08 UTC, gw-study commented on src/main/java/calculator/Operator.java
> +                .findFirst().orElseThrow(() -> new IllegalArgumentException("올바른 연산자가 아닙니다."));
스트림 활용 Good~👍
코드가 술술 읽힙니다 :)

2021-06-09 02:08 UTC, gw-study commented on src/test/java/calculator/CalculatorTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
피드백 적용 잘해주셨네요✔

2021-06-09 03:32 UTC, AyoungLim1103 commented
Step2 두번째 피드백 반영하여 리뷰요청 드립니다 :)

2021-06-09 04:44 UTC, gw-study approved these changes
피드백 빠르게 반영해주셔서 감사해요😄

소소한 코멘트하나 남겨놓았는데요,
다음 단계 진행하시면서 적용해주시면 될거 같습니다.

빠른 진행을 위해서 이번 단계는 여기서 머지 하도록 하겠습니다.

다음단계는 이번미션의 메인구현입니다. 지금까지 학습하신 단위테스트 작성방법을 활용하여 구현해 보아요.
그럼 화이팅 입니다~~ 💪

2021-06-09 04:44 UTC, gw-study commented on src/test/java/calculator/CalculatorTest.java
> -    @Test
이건 굳이 삭제 하지 않으셔도 될거 같아요.
아니 미션의 요구사항을 충족할려면 있어야 하는게 맞을거 같습니다.😄

2021-06-09 04:45 UTC, merged

2021-06-09 04:48 UTC, gw-study reviewed
아까 리뷰한 내용을 수정하다가 이상하게 되어버려서 다시 코멘트 남겨요ㅋ

2021-06-09 04:48 UTC, gw-study commented on src/test/java/calculator/CalculatorTest.java
> -    public void testBlank() {
이건 굳이 삭제 하지 않으셔도 될거 같아요.
아니 미션의 요구사항을 충족할려면 있어야 하는게 맞을거 같습니다.😄