step2 리뷰 요청드립니다
gw-study/java-racingcar pull request #13
Opened 2021-06-09 00:12 UTC by dahyunja

[2단계 - 문자열 계산기]

- 문자열 사칙 연산 계산기 구현

2021-06-09 04:33 UTC, gw-study requested changes
이번 스텝 빠르게 요청주셨네요👍

이번 스텝의 주요 내용은 주어진 문자열을 올바르게 계산하느냐 인거 같아요.

작성하신 테스트 케이스중에 사칙연산에 대한 테스트를 수행하는 코드가 있는데요,
코멘트에도 남겨놓았지만 
실수형의 테스트 값이 아닌 문자열의 테스트 값을 사용한 케이스를
작성하는게 어떨까 생각이 됩니다.🤔
이렇게 하자면 아마도 현재 사칙연산을 수행하는 메소드는 사라지고
하나의 메소드를 사용하게 될거예요😄

몇가지 코멘트를 남겨놓았으니 확인하시고 다시한번 리뷰 요청 부탁드릴께요🙇‍♂️
퐈이팅예요~🔥🔥🔥

2021-06-09 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +            calculator.stringCalculator(input);
저도 처음에는 지금처럼 테스트 코드를 짯었는데요
아래처럼 하는게 조금더 보기 편하고 일반적이라고 하네요.😄
```suggestion
        assertThatThrownBy(() -> calculator.stringCalculator(input))
                .isInstanceOf(IllegalArgumentException.class);
```

2021-06-09 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +    @CsvSource(value = {"2 + 3 * 4 / 2:10", "3 - 2:1", "6 / 3 - 1 * 4 + 5:9"}, delimiter = ':')
`@ParameterizedTest`사용 잘해주셨어요👏

한가지 더 욕심을 내자면 `name`속성을 사용해서 displayname을 커스터마이징 해볼 수 있을까요?

2021-06-09 04:33 UTC, gw-study commented on src/main/java/Calculator.java
> +    int plus(int no1, int no2){
프로덕션 코드에서는 접근지정자는 필수로 선언해주세요

다른 메소드들도 모두 확인 부탁드립니다.

2021-06-09 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +        assertThat(calculator.plus(2,3)).isEqualTo(5);
```suggestion
        assertThat(calculator.stringCalculator("2 + 3")).isEqualTo(5);
```
이런식으로 변경해 볼수 있을거 같아요😄

다른 테스트도 동일하게 변경 부탁드려요~

2021-06-09 04:33 UTC, gw-study commented on src/main/java/Calculator.java
> +    int stringCalculator(String input){
사칙연산 기호별로 분기를 해주셨군요!
저도 과정진행할때 이렇게 했습니다.😄

과도한 if문은 많은 단점이 있어요(관련된 내용은 조금만 검색을 해보시면 찾으실 수 있을거에요)
그래서 이런 if문을 사용하지 않도록 몇가지 방법을 사용하는데요,
그중에 하나가 다형성을 구현하는 거예요.
이번 과정의 경우는 `enum`을 사용해서 if문을 제거해 보시길 바랄께요.🙏
(힌트 : enum 에도 스테틱이 아닌 맴버 필드와 메소드를 정의할 수 있어요.)

2021-06-10 14:39 UTC, dahyunja commented
피드백 적용했습니다. 리뷰 요청 드립니다.

2021-06-10 21:36 UTC, gw-study approved these changes
안녕하세요😀

피드백 빠르게 적용해 주셔서 감사합니다👍

enum활용을 잘 해주시고 메소드 역할 분담도 적절하게 나누어 주셔서
코드가 훨씬 정돈되고 깔끔해 졌습니다.
읽는데도 수월했어요👏👏

접근지정자 관련해서 코멘트 드린 부분이 있는데요,
다음 단계에 적용 부탁드리겠습니다.🙏

이번 단계는 여기서 머지하도록 하겠습니다.
다음 단계는 이번 미션의 메인구현입니다. 지금까지 학습한 단위테스트 방법을 활용하여 구현재 보아요 :)
끝까지 화이팅입니다🔥🔥🔥

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Calculator.java
> +    protected int stringCalculator(String input){
`protected`로 선언한 이유가 있을까요?🤔
전 `public`이 더 나아 보입니다😄

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Calculator.java
> +            splitStringToInt[i+1] = Operator.calculate(splitStringToInt[i-1], splitStringToInt[i+1], splitString[i]);
if문과 반복이 사라지니 코드가 훨씬 깔끔해졌습니다👍👍👍

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Operator.java
> +    DIVIDE("/", (a, b) -> a / b);
enum활용 Good💯👍

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Operator.java
> +    private final IntBinaryOperator intBinaryOperator;
final사용 잘 해주셨습니다👏

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Operator.java
> +    protected static int calculate(int a, int b, String sign) {
여기 `protected`도 `public`으로 변경해 볼 수 있을까요?

2021-06-10 21:36 UTC, gw-study commented on src/main/java/Operator.java
> +                .orElseThrow(IllegalArgumentException::new);
스트림을 활용해서 연산자를 찾으셨네요!👍👍👍

2021-06-10 21:36 UTC, gw-study commented on src/test/java/CalculatorTest.java
>  public class CalculatorTest {
모든 피드백을 적용해 주셔서 감사해요😄

2021-06-10 21:37 UTC, merged