Step3 리뷰요청드립니다.
gw-study/java-racingcar pull request #14
Opened 2021-06-14 15:08 UTC by pkh11

2021-06-15 04:35 UTC, gw-study requested changes
만들어 주신 자동차 경주 프로그램이 아주 잘 실행이 되네요👍
커밋 메세지도 잘 나누어 주셨어요👏

코드에 대한 리뷰를 하다가 MVC관련 부분을 말씀드리면 좋을 거 같아서
아래 간략하게 내용을 조금 남겨 봅니다.

자바 뿐만 아니라 객체를 지향하는
일반적인 프로그램의 구조는 Model-View-Controller 방식의 MVC방식을
전통적으로 따르고 있어요. (이렇게 하면 장점이 많이 발생하거든요😄)
뭐 요즘에는 새로운 구조도 많이 나오고 있긴 하지만
기본 Base는 MVC방식을 따르고 있다고 생각합니다.

이번 자동차 경주도 그 크기는 작지만 MVC요소들을 모두 가지고 있는데요,
자동차의 전진(move)을 위한 비지니스(도메인, 모델) 담당,
전진한 결과를 화면에 표현하는 출력 담당,
그리고 이 둘에 대한 조합을 적절하게 연결해주는 컨트롤러가 그 예가 될거 같네요

작성해 주신 코드를 이것과 대비해 보면
`Competition` 은 컨트롤러,
`InputView` `ResultView` 는 View담당,
그외 클래스는 도메인(=모델) 담당이라고 할 수 있을거 같아요.
기본적인 큰 구조를 이렇게 생각해 보면,
각각의 역할을 충실히 할 수 있도록 변경할 수 있는 부분이 보이는거 같습니다.

이와 관련된 세부적인 내용을 코멘트로 조금 더 덧붙여 놓았는데요,
진행하시면서 잘 안되거나 궁금한 부분이 있으시면 언제든지 DM날려주세요.
같이 고민해 보도록 하겠습니다.😄

그럼 리뷰요청 다시 기다리도록 하겠습니다.🙇‍♂️

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +class Car {
접근지정자 사용을 필수로 해주세요 :)

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +    private static int LIMIT_RANDOM_NUMBER = 4;
final키워드를 추가하면 이 변수는 값을 변경 할 수 없게됩니다.
즉, immutable(불변) 상태가 되는거죠😄
저는 `final` 키워드를 자주사용하려고 노력하는데요, 컴파일타임에 불변임을 보장해서 사이드 이펙트(=버그 발생 가능성)를 줄여줄 수 있기 때문이에요.
final 추가를 고려해주세요~

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +class Position {
`Car`클래스 안에서 `Position`클래스를 같이 정의한 이유가 있을까요?🤔
보통 `Car`와 `Position`을 각각 클래스로 분리하는게 일반적인 것 같습니다.

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +    int value;
`Position`클래스는 캡슐화가 필요할 것 같네요.
```
public class Position {
    private final String distance;
    
    public Position(String distance) {
        this.distance = distance;
    }

    public String getDistance() {
        return distance;
    }
}
```
이런 방식으로 작성을 하면 `Position`의 생성자를 통해서만 distance 값을 할당할 수 있습니다.
이렇게 변경해 볼 수 있을까요?

2021-06-15 04:35 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    private ResultView resultView;
UI를 담당하는 `InputView` `ResultView`는 도메인 객체(예:`RacingCarCompetition`)를 참조할 순 있지만
반대로 도메인에서는 UI객체를 참조하는 건 객체 사이의 결합도가 높아지게 됩니다.
객체 간의 결합도가 높아지게 되면 수정사항 발생시 테스트해야 할 범위도 넓어지게 되구요.

해당 클래스에서는 `RacingCarCompetition`과 관련된 비지니스 로직만
처리하고 입출력은 XxxxView와 같은 객체에서 역할을 수행하도록 분리해주세요.

2021-06-15 04:35 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +        return cars;
이번단계 부터는 자바 코드 컨벤션을 지키도록 노력해 볼까요?
[네이버 자바 코드 컨벤션](https://naver.github.io/hackday-conventions-java/) 
인텔리제이를 사용한다면 `Save Actions`플러그인을 사용하면 많은 부분을 자동화 할 수 있습니다😄

2021-06-15 04:35 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +        }
입출력 담당은 UI관련 클래스에 일임해주세요🙏

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +    public void move(int randomNumber) {
숫자를 파라메터 인자로 받을 수 있도록 설계 잘해주셨어요👍
이렇게 하면 테스트하기도 한결 수월해지겠네요👏

2021-06-15 04:35 UTC, gw-study commented on src/main/java/Car.java
> +        System.out.println(position.distance);
출력에 대한 역할은 UI클래스가 하도록 변경 부탁드릴께요🙏

2021-06-15 04:35 UTC, gw-study commented on src/main/java/InputView.java
> +    private static String QUESTION_ABOUT_NUMBER_OF_TIMES = "시도할 회수는 몇 회 인가요?";
메세지를 상수로 잘 표현해주셨네요👍
`final`키워드 추가도 고려해봐 주세요 :)

2021-06-15 04:35 UTC, gw-study commented on src/main/java/InputView.java
> +        return isValidInput(sc.nextLine());
`nextInt()`를 사용하면 숫자만 입력 받을 수 있어요😁

2021-06-16 13:09 UTC, pkh11 commented
피드백 관련해서 수정하였습니다. 

MVC패턴에 맞게 UI(View) <-> 컨트롤러(Controller) <-> 도메인(Model)로 나누어 구성하였습니다.😀

2021-06-17 07:23 UTC, gw-study approved these changes
피드백드린 부분을 적용하실려고 많이 노력한게 보입니다👍👍👍
각각의 역할에 따라 MVC로 잘 분리해 주셨어요👏👏👏

아직 접근 지정자 키워드 사용, 캡슐화 등과 같이
수정을 해 볼 부분이 보이고 있어서 관련한 코멘트를 남겨놓았습니다.

빠른 과정 진행을 위해서 이번 단계는 여기서 머지 할께요.
남겨드린 피드백은 다음 단계에서 꼭!적용해 보시길 바라겠습니다.

다음 단계도 쉽지 않을지 몰라요😅
지치지만 말고 끝까지 완주 해보시길 바라겠습니다🙇‍♂️

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Car.java
> +    Car(String defaultDistance, int defaultValue) {
접근지정자가 필요한 곳에는 필수로 기입부탁드립니다🙏

2021-06-17 07:23 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +public class RacingCarCompetition {
지금 작성한 코드에는 고민해야 할 부분이 좀 보이는거 같아요.
- 인스턴스 변수는 외부에서 접근하지 못하도록 캡슐화를 해주는 것이 중요합니다.
`numberOfCar` `numberOfTimes`와 같은 인스턴스 변수는 가능한 `private`로 사용해 주시는 것이 좋습니다.
- 클래스 내부에서만 사용되는 메소드는 `private`로 지정해 주세요.
- `final`을 사용할 수 있으면 불변함을 보장하게 되어 프로그램이 가지는 사이드 이펙트(side effect, 부수효과)를
줄일 수 있습니다. 이말은 버그 발생할 확률이 줄어든다는 말이예요.

위에 내용들을 포함해서 코드를 수정하면 아래처럼 변경할 수 있을거 같아요
```java
import java.util.ArrayList;
import java.util.List;

public class RacingCarCompetition {

    private final int numberOfCar;
    private final int numberOfTimes;

    public List<Car> cars = new ArrayList<>();
    public List<String[]> history = new ArrayList<>();

    public RacingCarCompetition(int numberOfCar, int numberOfTimes) {
        this.numberOfCar = numberOfCar;
        this.numberOfTimes = numberOfTimes;
        readyForCar();
    }

    private void readyForCar() {
        for (int i = 0; i < numberOfCar; i++) {
            cars.add(new Car("-", 1));
        }
    }

    public void startRacing() {
        ....
    }

```
한가지 더 바라는 점이 있다면 `startRacing` 함수의 결과로
결과객체(DTO)를 반환하여 view에서 사용하게 된다면 좋겠네요!😁

2021-06-17 07:23 UTC, gw-study commented on src/main/java/ResultView.java
> +    ResultView(RacingCarCompetition competition) {
접근 지정자를 필수로 해주세요🙏

2021-06-17 07:23 UTC, gw-study commented on src/main/java/ResultView.java
> +    private RacingCarCompetition competition;
`final`키워드를 추가하면 불변임이 보장되어서 사이드 이펙트 효과를 줄일 수 있답니다😃

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Position.java
> +    int value;
`private` 를 지정해 주세요.
사용하고 있는 곳은 어떻게 변경해야 할지 고민해 볼 필요가 있을거 같습니다🙏

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Position.java
> +    public String getDistance() {
사용하지 않는 코드는 삭제 부탁드립니다🙏

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Position.java
> +    public int getIntegerDistance() {
일반적으로 getter의 명명규칙은 getXxxx 처럼 'get + 변수명'의 조합으로 사용합니다.
이렇게 명명이 되어 있으면 '아~이 메소드는 이 변수가 가지고 있는 값을 반환하겠구나' 라고
통상적으로 생각하도록 일종의 약속(?)이 되어 버렸어요😅
*자바빈 규약도 이 규칙을 따르도록 되어 있답니다ㅎ

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Position.java
> +    int value;
`value`라는 정의는 값이라고 해석이 되는데요,
이 이름을 변수명이라고 하기에는 너무나 많은 의미를 내포하고 있는거 같아요.
뭔가 들으면 딱 알아볼 수 있는 이름은 없을지 고민해 볼 수 있을까요?🤔

2021-06-17 07:23 UTC, gw-study commented on src/main/java/ResultView.java
> +class ResultView {
접근지정자가 누락되었습니다😱

2021-06-17 07:23 UTC, gw-study commented on src/test/java/RacingCarCompetitionTest.java
> +class RacingCarCompetitionTest {
테스트 케이스가 좀 부족해 보입니다ㅠ
반복되는 횟수에 대해 자동차가 얼마나 전진했는지에 대한 테스트를 추가 해볼수 있으면 좋겠어요.
예를 들면, '1대의 자동차를 3번 반복하면 3칸을 전진한다.' 라는 케이스인거죠

랜덤 함수를 사용하기 때문에 이 테스트가 쉽지 않을 수 있어요.
그래도 어떻게 하면 가능할지에 대해 고민해 보시면 많은 걸 얻어가실 수 있을거예요😃
* 힌트 : 자바의 Interface 를 생각해보세요

2021-06-17 07:23 UTC, gw-study commented on src/main/java/InputView.java
> +public class InputView {
![image](https://user-images.githubusercontent.com/84048349/122349197-f7822180-cf86-11eb-96a0-d3c6f29ee7b2.png)
이렇게 입력이 되면 어떻게 될까요?😱
값에 대해 검증을 하는 방법도 있지만 입력 값에 대해 부터 제한을 하는 방법도 있습니다
앞에 드린 [피드백](https://github.com/gw-study/java-racingcar/pull/14#discussion_r651439594)을 참고해 주세요😁

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Competition.java
> +    public static void main(String[] args) {
`main`메소드가 컨트롤러 역할을 잘 수행하고 있네요👍👍👍

2021-06-17 07:23 UTC, gw-study commented on src/main/java/Competition.java
> +        competition.readyForCompetition();
`readyForCompetition` 으로 자동차가 경주할 준비를 했으면
다음에는 경주 시작을 기대할거 같아요😃
비지니스 로직을 흐름대로 기술해주면 코드 읽기가 아주 용이해집니다 :)

2021-06-17 07:24 UTC, merged