Step3 리뷰 요청드립니다
gw-study/java-racingcar pull request #17
Opened 2021-06-15 15:15 UTC by dahyunja

[3단계 - 자동차 경주]

기능 요구사항
- 초간단 자동차 경주 게임을 구현한다.
- 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
- 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.

2021-06-15 23:54 UTC, gw-study requested changes
안녕하세요!3단계 구현 잘해주셨어요👏
커밋 메세지도 잘 남겨주셔서 리뷰하는데 수월했습니다👍

static 메소드 관련한 내용과
UI로직과 도메인 로직 분리 관련 내용,
그리고 테스트 코드에 대한 코멘트 남겨 놓았어요.

UI로직(View)과 도메인 로직(Model) 분리 관련한 내용을 조금 더 설명드리면,
View는 도메인을 참조할 수 있지만
반대로 도메인이 View를 참조하게 되면 결합도가 증가하여
View에 수정사항이 발생하는 경우, 관련된 도메인도 모두 다 검증(테스트)해야 하는
상황이 발생합니다.
그래서 View와 도메인(Model)을 분리하고 분리한 각각을 조합하는 컨트롤러가 필요하게 되는 것이지요.

피드백 드린 내용 확인 해보시고 다시 한번 요청 부탁드리겠습니다🙇‍♂️
진행하시다가 궁금한 내용이 있으시면 언제든지 DM보내 주세요.
바로는 아닐지 모르지만 최대한 빠르게 답장 드리도록 하겠습니다😃

퐈이팅이요~🔥

2021-06-15 23:54 UTC, gw-study commented on README.md
> +* 자동차의 상태를 출력하는 기능
기능목록 정리👍

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    private final int number;
변수이름을 조금 더 의미 있는 이름으로 지어보는게 좋을거 같아요.
예를들면, `car` -> `countOfCars`, `number` -> `countOfRounds` 처럼요😃

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    public int getRacingCarInput(){
getter로 사용하는 메서드 명칭은 일반적으로 getXxxx() 처럼 작성하는데요,
지금 같은 경우는 `getCar()`라고 명명할 수 있을거 같습니다😃
정해져 있는 규칙은 아니지만 하나의 약속(?)으로 굳어져서,
메소드명만 보고도 '아!이 메소드를 사용하면 이런걸 가져올 수 있겠구나' 라고 인식을 하게 되었어요😅

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    }
```java
    public RacingCar(int car, int number) {
        this.car = car;
        this.number = number;
        this.cars = new int[car]; //추가
    }
```
생성자에서 이렇게 추가를 하고
```suggestion
    public int[] getCars(){
        return cars;
    }
```
이렇게 변경해 보는건 어떨까요?

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCarMain.java
> +        ResultView.resultViewStart();
UI관련 로직은 도메인 로직과 분리해주세요🙏

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCarMain.java
> +            ResultView.resultView(cars, i);
UI관련 로직은 도메인 로직과 분리해주세요🙏

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RandomNumber.java
> +    public static int makeRandomNumber(){
랜덤한 숫자를 생성하기 위한 역할을 잘 분리해주셨어요👍

2021-06-15 23:54 UTC, gw-study commented on src/test/java/racingcar/step3/RacingCarTest.java
> +class RacingCarTest {
테스트 케이스를 꼼꼼하게 상황별로 잘 분리해서 작성해주셨어요👍

다만, 현재 작성한 코드는 테스트코드라고 보기가 어려워요.
테스트는 주어진 값으로(given), 어떤일을 수행했을 때(when), 어떤 결과를 기대(then)하는
일련의 과정들을 담고 있어야 하는데
이 코드는 when 만 존재하고 있는 것 같습니다.😱
(업무랑 병행하느라 바쁘셔서 깜빡하신 거 같아요ㅎㅎㅎ)

assertThat과 같은 값을 검증하는 로직을 사용해서 테스트 코드 작성을 부탁드릴께요🙏

*테스트케이스중에 '랜덤값 생성 테스트'는 이번 단계 핵심중에 핵심이라고 할 수 있어요. 많이 고민해 보시길 바랄께요😁

2021-06-15 23:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCarMain.java
> +            if (RandomNumber.makeRandomNumber() >= 4) {
4는 매직넘버 입니다. 수정해볼 수 있을까요?
('자바 매직넘버' 정도로 검색하면 많은 힌트를 얻으실 수 있을거예요)

2021-06-23 14:26 UTC, dahyunja commented
피드백 적용했습니다. 리뷰 요청 드립니다.

2021-06-24 11:16 UTC, gw-study approved these changes
안녕하세요!!
잊지않고 리뷰 요청을 주셨네요!
열심히 해주셔서 감사해요~👍😄

이전 단계 피드백도 다 적용해주시고 커밋메세지도 잘 나눠주셔서 리뷰가 조금 더 수월할 수 있었습니다😀
변수명이라던지 코드의 짜임새가 조금씩 발전하고 있는거 같아서 제가 뿌듯한 기분입니다ㅎ

제가 다현님 코드를 보면서 의견을 드릴 수 있는 부분을 클래스별로 아래에 조금 정리를 했어요.단계를 계속 진행하면서도 생각해 볼 수 있는 이야기들이라서 한번 참고해 보셨으면 좋겠습니다. 

RacingCarMain
 - 자동차경주 프로그램을 실행하기 위한 메인 클래스인걸로 생각됩니다.(맞겠죠?ㅎ)
 - 이 프로그램을 다른 사람이 사용할 수 있도록 API로 만든다고 가정하면 프로그램을 배포할 때, 메인 클래스는 제외합니다. 그렇기 때문에 메인클래스는 프로그램을 실행하는 역할만 하도록 설계하는게 제일 명확하다고 생각하는데요, 아래 예처럼 말이죠 😁
 ```java
    public static void main(String[] args) {
        new RacingCarController().run();
    }
 ```
 - 메인클래스가 컨트롤러 역할을 할 수도 있지만 이렇게 컨트롤러 역할을 하는 클래스를 따로 빼 보는건 어떨까요?🤔
 - `move`함수는 자동차를 움직이는 행위를 하도록 하고 있어요. 이 행위는 자동차 경주 프로그램의 핵심 로직이라고 할 수 있는데요 이런 비지니스 로직은 도메인(모델)레벨에 위치하는게 좋습니다 :)
 `RacingCar` 클래스가 도메인 역할을 하는거 같은데요 이쪽으로 옮겨볼 수 있을까요?(이렇게 한다면 많은 getter들이 사라지는 효과도 있을거 같은데요?🤔)
 
RacingCar
 - 자동차 경주의 핵심 요소들을 관리하는 클래스네요
 - 위에서도 말씀드렸지만 자동차 전진에 대한 역할도 이곳에서 하는 것이 적절해 보입니다😁

InputView/ResultView
 - 입력과 출력을 담당하는 클래스네요👍
 - 여기서는 메소드를 static으로 선언할 이유가 없다고 생각되요. static으로 선언한 이유가 `main`함수에서 호출하기 위함이라면
 ```java
    public static void main(String[] args) {
        InputView inputView = new InputView();
        inputView.test();
    }
 ```
이런식으로도 충분히 사용할 수가 있습니다.
혹시 다른 이유에서 static을 사용하셨다면 같이 고민을 해보면 좋을거 같아요😀

빠른 진행을 위해서 이번 단계는 여기서 머지하도록 할께요.
제가 드린 피드백은 다음 단계에서 생각해보면서 적용해보시면 좋을거 같습니다 :)

혹시 궁금한 내용이 있다면 언제든지 DM주셔도 괜찮아요!
끝까지 파이팅!!🔥🔥🔥

2021-06-24 11:16 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    private ArrayList movementOfCar;
ArrayList는 제네릭을 활용하여 정의할 수 있을거 같아요😀
제네릭을 사용하면 형변환에 대해 자유로와 진답니다🎶

2021-06-24 11:16 UTC, gw-study commented on src/test/java/racingcar/step3/RacingCarTest.java
> +class RacingCarTest {
테스트케이스 작성 잘해주셨습니다👍

2021-06-24 11:16 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCarMain.java
> +    public static void move(RacingCar racingCar, int[] cars, ArrayList movementOfCar) {
`move`는 핵심로직이예요!
도메인(모델) 클래스로 이동부탁드려요🙇‍♂️

2021-06-24 11:16 UTC, merged