Step3 리뷰 요청 및 문의드립니다.
gw-study/java-racingcar pull request #18
Opened 2021-06-16 01:02 UTC by a-ri-mu

차장님 안녕하세요.

Step 3 리뷰 요청드립니다. 

또한, 랜덤 케이스에 대한 테스트를 어떻게 진행해야 할 지 궁금합니다.

isBetween(0, 9) 으로 설정은 해 두었는데, 정확한 방법은 아닌 것 같아서요~ 
- assertThat(carRacing.makeRandom()).isBetween(0, 9); 

혹시 좋은 방법이 있다면 추천 부탁드립니다.

감사합니다:)

2021-06-16 05:45 UTC, gw-study requested changes
이번 단계 구현 잘해주셨어요👏👏👏
커밋메세지도 잘 나줘 주셔서 리뷰하는데 편했습니다.👍

몇가지 고민을 해보면 더 좋은 코드가 만들어 질거 같아서
코멘트를 남겨 놓았습니다.

그리고 아래처럼 문의를 주셨는데요,
이번 단계에서 아주아주 중요한 부분에 대한 궁금증입니다.👍

> 또한, 랜덤 케이스에 대한 테스트를 어떻게 진행해야 할 지 궁금합니다.

코멘트로도 적어 놨지만, 간략하게 한번더 설명을 드리면
테스트 가능한 부분과 테스트 하기 힘든 부분을 분리해 내는게 방법이라고 할수 있을거 같아요.

이 랜덤 함수를 사용하는 함수를 찾아서
함수안에 인라인으로 사용하는 방법이 아닌,
더 상위수준으로 끌어올려야 하는데요,
상위수준으로 끌어올리기 위해서는 메소드의 파라메터로 변경하는 방법이 있을거 같아요.

코멘트 드린 내용과 같이 생각해 보시고 해결 방법이 번뜩 떠올랐으면 좋겠네요😁

고민하다가 잘 안풀리거나 안되겠다 싶으면 언제든지 DM주세요.
제가 바로는 답장을 못 드릴 수도 있지만 확인되는데로 회신 드리도록 하겠습니다😃

그럼 리뷰 요청 기다리겠습니다🙇‍♂️

2021-06-16 05:45 UTC, gw-study commented on README.md
> +* 전진하는 기능(0에서 9 사이에서 random 값을 구한 후 random 값이 4이상)
기능목록 정리 👍

2021-06-16 05:45 UTC, gw-study commented on src/main/java/Car.java
> +    public int makeRandom() {
랜덤한 숫자를 생성하는 메소드 분리👍

2021-06-16 05:45 UTC, gw-study commented on src/main/java/Car.java
> +        return random.nextInt(10);
```suggestion
        return new Random().nextInt(10);
```
저는 이렇게 사용하는게 좀 더 직관적인거 같아서 좋아합니다😅

2021-06-16 05:45 UTC, gw-study commented on src/main/java/Car.java
> +    public String addMove(String str) {
이 메소드는 자동차 경주 결과를 **출력**하는 부분 같아보입니다.
View와 관련된 로직은 도메인과 분리해 볼 수 있을까요?

2021-06-16 05:45 UTC, gw-study commented on src/main/java/Car.java
> +    public void racingStart(int carCnt, int tryCnt) {
`racingStart`는 너무 많은 일을 하고 있는거 같아요😂
자동차를 준비(초기화) 하고,
입력 횟수만큼 반복 하고,
또 다시 자동차 대수 만큼 반복을 하면서
출력까지 담당하는 역할을 하고 있네요.
메소드(또는 클래스)가 너무 많은 일을 하게 되면 나중에 여러가지 문제를 발생 시키는 원인이 된답니다.

클래스명과 메소드명을 만들때는 그 역할이 무엇인지 고민을 하고
작성을 하게 되는데요(그래서 기능목록을 작성한 부분도 있습니다)
`Car`라는 클래스는 어떤 `행동`과 `상태`를 담고 있어야 하는지
고민을 좀 해볼 필요가 있을거 같아요.

제가 했던 경험을 좀 말씀드리면,
제가 만들었던 `Car`에는 현재 위치(position) 상태만 가지고 있고,
전진(move)을 할 수 있는 행동만 가지고 있었던 것 같습니다.
이건 정답이 아니기 때문에 참고만 해보세요😃

제가 드리고 싶은 내용은 메소드가 최소한의 행동만 할 수 있도록
필요하면 클래스를 만들더라도 역할을 분리했으면 하는 내용이예요 :)

2021-06-16 05:45 UTC, gw-study commented on src/main/java/RacingCar.java
> +    public static void main(String[] args) {
자동차 경주 실행을 위한 main함수 잘 만들어주셨어요👏

이번 과정에서는 콘솔에 모든 내용을 출력하기 때문에 `main`함수가
컨트롤러 역할을 해야할 부분이 있습니다.
간략히 조금 설명드리면 컨트롤러는 View와 도메인의 조합을 담당한다고 할 수 있을거 같아요.
어떻게 하면 컨트롤러 역할을 할 수 있을지 고민해 볼 수 있을까요?🤔

2021-06-16 05:45 UTC, gw-study commented on src/main/java/ResultView.java
> +    void printCar(String[] carArray) {
접근 지정자는 항상 명시하도록 해주세요😂

2021-06-16 05:45 UTC, gw-study commented on src/test/java/CarTest.java
> +class CarTest {
테스트 케이스 작성 잘해주셨습니다✔

한가지 더 욕심을 부리자면
시도한 횟수만큼 자동차가 전진 또는 정지 하여 예상되는 결과를 테스트해 볼 수 있을까요?
예를 들면, 3번 시도했을 때 자동차가 전진한 결과는 3이다 라는 테스트 인거죠

2021-06-16 05:45 UTC, gw-study commented on src/main/java/Car.java
> +    public String[] initArray(String[] stringArr) {
`initArray`는 너무 광범위한 이름 같아요😂
어떤걸 초기화 하려고 하는지 메소드명에 나타나면 좋을 거 같습니다.
그리고 이 메소드는 외부에서 참조할 필요가 없을거 같은데요
`public`보다는 `private`가 적절하지 않을까 생각됩니다🤔

2021-06-16 05:45 UTC, gw-study commented on src/test/java/CarTest.java
> +        assertThat(carRacing.makeRandom()).isBetween(0, 9);
문의 주신 부분이네요😃
단순히 `makeRandom()` 함수가 0~9까지 숫자를 잘 생성하는지
테스트 하는거라면 이렇게 테스트 한 것에 이견은 없습니다
(물론 반복문 등을 통해서 수많은 케이스를 검증해야 정확한 테스트가 되겠지만요😁)

사실 이런 랜덤한 함수를 테스트하기란 쉽지가 않습니다.
이 랜덤 함수를 사용하는 곳을 테스트하기란 더 힘들죠(`racingStart`함수가 되겠네요)

이런 케이스에 대해 테스트가 가능하도록 변경해 보는 것이 이번 단계의 큰 핵심 내용인데요,
방법을 조금 설명을 드리면
- 일단 테스트 가능한 코드와 테스트하기 힘든 코드를 분리합니다.
지금 코드에서는 `racingStart`에서 `makeRandom` 을 분리해 내는 거죠
예를 들면, 아래 코드는
```java
    public void move() {
        if (getRandomNo() >= 4)
            this.position++;
    }
```
이렇게 변경할 수 있습니다.
```java
    public void move(int number) {
        if (number >= 4)
            this.position++;
    }
```
- 그리고 이것을 다시 interface를 사용하도록 변경하면 테스트가 가능해집니다.
```java
public interface MovableStrategy {
    boolean isMove();
}
```
*interface를 참조하는 방법과 테스트코드 구현은 고민해보시길 부탁드려요😂

위에 내용이 어려울 수도 있을거 같은데요 그래도 한번 고민을 해보시면 해결책을 찾으실 수 있을거예요😁

2021-06-25 00:40 UTC, a-ri-mu commented
차장님 안녕하세요:)

구조를 다시 리팩토링하였으며, 
피드백 주신 내용처럼 인터페이스를 활용해 테스트하는 방안을 적용했습니다.
- MoveStrategy, RandomMove.java 
- MoveableStrategy, NonMoveableStrategy.java (test를 위한 클래스)

move() 리팩토링은 아래와 같이 진행되었습니다. 

1. 테스트 가능한 코드와 불가능한 코드 분리
public String move(int value) {
        if (value >= RANDOM_LIMIT_NUM) {
            curPosition += "-";
        }
        return curPosition;
}

2. 인터페이스 전략 패턴 적용으로 인한 move 메소드 재수정
    public String move(MoveStrategy moveStrategy) {
        if (moveStrategy.isMove()) {
            curPosition += "-";
        }
        return curPosition;
}

맞게 적용한 부분인지 잘 모르겠습니다ㅎㅎ 
혹시 좀 더 고려해야 할 부분이 있다면 피드백 부탁드립니다.

감사합니다.

2021-06-25 11:00 UTC, gw-study approved these changes
안녕하세요😄
업무랑 병행하면서 과정 진행하시느라 힘드실텐데 이전 피드백을 너무 잘 적용해 주셨어요👍
코드가 전반적으로 잘 짜여진 느낌입니다 :)

인터페이스는 잘 사용해 주셨는데
구현한 부분이 약간 아쉬움이 있네요😂
현재 `MoveStrategy`인터페이스의 구현체는
`MovableStrategy` `NonMovableStrategy` `RandomMove` 의 세개가 있는데요,
구현체는 하나만 있어도 충분할 것 같습니다.
그리고 구현체를 아래처럼 구현하면 좋을거 같다는 의견이예요.
```java
public class MovableStrategy implements MoveStrategy {
    private static final int MOVABLE_NUM= 4;

    @Override
    public boolean isMove(int number) {
        return number >= MOVABLE_NUM;
    }
}
```
이렇게 구현을 하고 테스트 방법은 제가 코멘트를 달아드린 내용을 참고해 보시면 좋을거 같아요😄

그리고 `Car`와 `RacingCar`의 역할이 중복된 느낌인데 하나로 합쳐도 괜찮을 거 같은 의견입니다.
(이건 제 생각이니 참고만 해봐주세요)

그 외 다른 부분에 몇개 코멘트를 남겨 놓았습니다. 과정 진행하면서 생각해 보시고 적용해 보시면 좋을거 같아요

빠른 진행을 위해서 이번 단계는 여기서 머지하도록 할께요.
주말 잘 보내시고 다음 리뷰 요청 기다리도록 하겠습니다🙇‍♂️
파이팅🔥🔥🔥

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/Car.java
> +    public String move(MoveStrategy moveStrategy) {
브라보!!피드백을 완벽하게 적용해주셨어요👏👏👏
인터페이스를 파라메터로 전달하게 되면 설계가 굉장히 유연해져요😁

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/Car.java
> +    private static final int RANDOM_LIMIT_NUM = 4;
이건 사용하지 않는 코드가 되었네요😂
삭제부탁드려요🙏

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/MoveStrategy.java
> +public interface MoveStrategy {
인터페이스 사용👍👍👍

2021-06-25 11:00 UTC, gw-study commented on src/test/java/CarTest.java
> +        }
인터페이스를 사용한 설계를 한 덕분에 랜덤한 숫자에 상관없이
프로덕션 코드를 테스트해 볼 수 있도록 변경이 되었어요!!!👏👏👏
아래처럼 말이지요
```suggestion
        for (int i = 0; i < 3; i++) {
            car.move(new MoveStrategy() {
                @Override
                public boolean isMove() {
                    return true;
                }
            });
        }
```
이렇게 변경할수 있구요,
이걸 람다를 사용하면 다시 아래처럼 간단하게 표현할 수 있습니다.
```java
        for (int i = 0; i < 3; i++) {
            car.move(() -> true);
        }
```
이렇게 인터페이스를 메소드의 인자로 사용하게 되면
테스트에서 인터페이스의 내용을 구현하여 내가 행동을 제어할 수 있어서
원하는 테스트 결과값을 얻을 수 있답니다😁

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/Main.java
> +        resultView.printCar();
이런식으로 변경하면 어떨까요?
생성자를 사용하면 클래스 초기화 기능을 할 수 있고 값에 대한 검증도 같이 수행할 수 있는 장점이 있습니다😄
```suggestion
        InputView inputView = new InputView();

        RacingCar racingCar = new RacingCar(inputView.carCount(), inputView.tryCount());
        RacingCarResult result = racingCar.start();

        ResultView resultView = new ResultView(result);
        resultView.printCar();
```

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/RacingCar.java
> +            car.move(new RandomMove());
랜덤 숫자를 먼저 생성하고 파라메터로 전달을 받도록 설계하면
테스트가 가능한 부분과 그렇지 않은 부분을 분리할 수 있을거 같아요🤣
```java
int randomNumber = Random().nextInt(10);
car.move(randomNumber);
```
이런식으로 말이지요🤔

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/ResultView.java
> +        }
이 부분은 도메인(모델)이 담당해야 할 부분입니다😂
`RacingCar` 로 옮기는게 좋을거 같다는 의견이예요 :)

그리고 하나 덧붙이면 `racingCar.tryCnt` 이렇게 사용하는건 지양해 주세요.
값이 변경되어 부수적인 효과 즉, 버그가 발생할 가능성이 높아지게 된답니다.😱
`racingCar.getTryCnt()` 이 정도로 바꿀 수 있을거 같아요(사실 getter도 안 쓰는게 제일 nice합니다😃)

2021-06-25 11:00 UTC, gw-study commented on src/main/java/RacingCar/RacingCar.java
> +    public int tryCnt;
```suggestion
    private final int tryCnt;
```
이렇게 선언할 수 있으면 불변함이 증명되어 부수효과가 발생하지 않도록 할 수 있어요.
이렇게 할려면 생성자를 사용해봐야 할거 같네요😀

2021-06-25 11:00 UTC, merged