Step4 리뷰요청드립니다.
gw-study/java-racingcar pull request #20
Opened 2021-06-28 01:26 UTC by pkh11

2021-06-28 06:29 UTC, gw-study requested changes
안녕하세요😊
이번 단계 자동차 우승자를 구하는 미션 잘 수행해주셨어요👏

고민을 많이 하면서 단계를 진행해주신거 같아요.
코드가 많이 심플하고 명확해 진 것이 보이긴 하지만
개인적으로 더 발전할 부분이 보여서 코멘트를 좀 많이 달아드렸습니다😱

그리고 한가지 덧붙이면 테스트케이스가 좀 부족해 보입니다.
아래와 같은 테스트를 추가해 볼 수 있을까요?
```
자동차 = A,B,C 3대
시도횟수 = 2회 라고 하면,
--1회
a.move(1);
b.move(2);
c.move(8);

--2회
a.move(1);
b.move(5);
c.move(6);

우승자는 A 입니다
```
이런 느낌으로 자동차별 시도횟수를 제어하여 우승자 예측이 가능한 테스트를 해볼 수 있으면 좋을거 같아요😄

지금 우리가 과정을 진행하면서 배우고자 하는 목표는
 - 입출력과 비지니스 로직(도메인)을 분리하고
 - 메소드 or 클래스를 작게 만들어서 테스트를 원할히 하며(=품질향상)
 - 기타 팀의 규칙, 즉 커밋/코드 컨벤션을 지키는

이런 훈련들을 하고 있어요.
과정 진행하시면서 다시한번 목표를 생각해 봐 주시면 코드에 힌트를 얻으실 수 있을지 모르겠습니다😁(너무 두리뭉실 한가요?ㅎ)

잘 안되거나 막히는 부분이 있으면 연락주셔도 괜찮고
제가 알려드린 다른 사람의 코드(github)를 보는 것도 많은 도움이 될 수 있습니다.

이번 단계는 Request Change 할께요
피드백 적용해서 다시 한번 리뷰요청 부탁드리겠습니다🙇‍♂️

2021-06-28 06:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    private final String[] names;
`final` 지정👍👍👍

2021-06-28 06:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    public void readyForCar() {
`readyForCar`메소드는 외부에서 호출되는거 같지 않아요.
그렇다면 `private`로 지정해 볼 수 있지 않을까요?

2021-06-28 06:29 UTC, gw-study commented on src/main/java/Position.java
> +    public int value;
클래스의 멤버 변수를 `public`으로 선언하게 되면 다른 누군가가
`Position.distance = "xxxxXXX"`과 같이 값을 아무렇지 않게 변경할 수 있게 됩니다.
이걸 방지하고자 멤버 변수를 `private`로 지정하고
 getter/setter를 사용하여 캡슐화를 합니다.

>여담이지만 사실 무분별한 게터/세터 사용도 지양해야 할 부분입니다.
기회가 되면 과정중에 이 부분을 다룰 수 있을지도 모르겠어요

그리고 `final` 키워드를 사용하면 멤버 변수가 불변임이 증명되어 값을 예측 가능할 수 있게 되는거죠.
(그래서 제가 `final`붙이라고 계속 얘기하는 거예요😁)

이 부분 외에도 이렇게 `public`으로 선언된 멤버 변수는 없는지 확인으 부탁드려요🙏

2021-06-28 06:29 UTC, gw-study commented on src/main/java/Competition.java
>  public class Competition {
입력과 출력 그리고 비지니스 로직 흐름대로
읽기 쉽게 코드를 잘 나눠주셨습니다👏

2021-06-28 06:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    public List<Car[]> startRacing() {
>indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

요구사항을 충족시켜 주세요😅

for문 안에 for문이 있는 구조라 코드 읽기가 쉽지 않아요ㅜ
메소드가 잘 읽히지 않고 여려가지 일을 하고 있다고 생각된다면
다른 메소드로 분리할 수 있는지 고려해 봐 주세요
단위가 작은 메소드로 분리를 하다보면 같은 역할을 하는 메소드를 모아서 다시 또 하나의 클래스가 될 수도 있고,
클래스로 분리가 되면 테스트하기가 용이해지는 코드가 만들어지는 경험을 하실 수 있을거예요👍

제 경험을 예로 말씀드리면 위에 코드는
```java
    public CarRacingResult startRacing() {
        while (isRoundContinue()) {
            car.전진();
            carRoundResultList.add(new CarRoundResult(cars));
            reduceRound();
        }

        return carRoundResultList;
    }
```
이런식으로 변경해 볼 수 있지 않을까 싶어요. 참고해봐 주세요🙏
*전 `Round`라는 시도횟수를 관리하는 클래스와
경주 결과를 관리하는 `CarRoundResult`클래스를 가지고 있었습니다.

2021-06-28 06:29 UTC, gw-study commented on src/main/java/Car.java
> +public class Car implements Comparable<Car> {
Comparable인터페이스를 구현해주셨네요👍

2021-06-28 06:29 UTC, gw-study commented on src/main/java/Car.java
> +    }
>else 예약어를 쓰지 않는다.

요구사항을 충족시켜 주세요😅

2021-06-28 06:29 UTC, gw-study commented on src/main/java/Car.java
>          return (int)(Math.random() * 10);
`10` 매직 넘버를 없애볼 수 있을까요?

2021-06-28 06:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +        Car[] last = history.get(numberOfTimes-1);
`numberOfTimes-1` 매직 넘버를 없애볼 수 있을까요?

2021-06-28 06:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +        Car first = new Car(last[0].position.distance, last[0].position.value, last[0].name);
콤마`.`를 너무 많이 사용하게 되면 코드 읽기가 어려워져요😭
다음단계 요구사항에도 나올테지만 `.`는 한번만 사용해보도록 노력해봐 주세요

2021-06-28 06:29 UTC, gw-study commented on src/main/java/InputView.java
> +    public String[] canSplit(String input) throws IllegalArgumentException {
>indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

요구사항을 충족시키도록 해주세요😭

메소드 네이밍에 대해 조금 설명을 드리자면,
`canXxxxx` `ableXxxx` `isXxxxx`와 같이 의문형으로 접두어를
사용하는 메소드명은 boolean 타입의 리턴값을 기대합니다.

메소드명도 조금 변경해야 할 부분이 보이는거 같네요😊

2021-06-28 06:29 UTC, gw-study commented on src/main/java/InputView.java
> +        name[0] = input;
매직넘버도 사용 지양해주세요!

2021-06-28 06:29 UTC, gw-study commented on src/main/java/ResultView.java
> +        }
>else 예약어를 쓰지 않는다.

요구사항을 충족하도록 해주세요😭

그리고 매직넘버 사용도 자제!(`int i = 0;` 이런건 괜찮습니다ㅎ)

2021-07-05 08:06 UTC, pkh11 commented
리뷰 요청 드립니다.

피드백 주신 부분 중에...
'이런 느낌으로 자동차별 시도횟수를 제어하여 우승자 예측이 가능한 테스트를 해볼 수 있으면 좋을거 같아요😄' 이 부분을 고민하다보니,
프로덕션 코드 수정을 많이 했습니다. (알려주신 자료를 참고했습니다.😅)
생각보다 시간이 오래 걸리더라구요...ㅎㅎㅎ

2021-07-05 23:29 UTC, gw-study requested changes
안녕하세요!😄

고민을 많이 한 흔적이 보이는거 같아요
코드가 많이 정리가 되었고 보기가 편해졌습니다👍
커밋 메세지도 잘 나눠주셔서 고민한 내용을 저도 같이 공유할 수 있었어요 :)

몇가지 코멘트 드린 내용이 있어요
확인해보시고 다시 한번 리뷰요청 부탁드릴께요🙏

이번 단계 마무리가 얼마 남지 않은거 같습니다!
조그만 더 파이팅이예요🔥🔥🔥

2021-07-05 23:29 UTC, gw-study commented on src/main/java/ResultView.java
> +        String alertOfWinner = winners.stream().map(Car::getName).collect(Collectors.joining(", "));
스트림 이용 잘해주셨어요!👍
```suggestion
        String alertOfWinner = winners.stream()
                .map(Car::getName)
                .collect(Collectors.joining(", "));
```
요렇게 점을`.` 기준으로 줄바꿈하는 방식이 일반적이랍니다😁

2021-07-05 23:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    public RacingCarCompetition(List<Car> cars) {
생성자 이용 잘해주셨어요!👏
한가지 욕심이 있다면 `public RacingCarCompetition(String[] names)` 가
`public RacingCarCompetition(List<Car> cars)`보다 위에 위치하는게 좋겠어요
코드를 신문처럼 읽으려면 위에서 부터 쭉 읽혀야 좋거든요 :)

2021-07-05 23:29 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    public List<List<Car>> history;
멤버변수가 `public`일 이유가 우리 과정엔 없을거 같다는 생각입니다.
멤버라면 무조건 `private final`부터 붙이고 시작하는건 어떨까요?😁

2021-07-05 23:29 UTC, gw-study commented on src/main/java/Car.java
> +        return (int)(Math.random() * LIMIT_MAX_RANDOM);
아 제가 저번 단계에 짚어드리지 못한 부분 같네요.
랜덤함수 생성은 java.util.Random 클래스의 nextInt(10) 메소드를 활용해주세요
(이렇게 하면 형변환도 필요없어질거 같습니다)

2021-07-05 23:29 UTC, gw-study commented on src/test/java/RacingCarCompetitionTest.java
> +    void distinctTest() {
테스트가 실패하네요😭
![image](https://user-images.githubusercontent.com/84048349/124523186-f9762c80-de30-11eb-9dc0-64da4683857d.png)

2021-07-05 23:29 UTC, gw-study commented on src/test/java/RacingCarCompetitionTest.java
> +    void multipleWinnerTest() {
테스트 케이스 작성 잘해주셨어요👍

2021-07-05 23:29 UTC, gw-study commented on src/main/java/Position.java
> +    private int value;
`Position`객체의 역할에 대해서 생각해 보면요,
자동자의 현재위치 정보에 대한 `상태`와
전진을 함으로써 이 `상태`를 변경하는 `행동`을 가지고 있어야 할 거 같다는 의견입니다.

그렇기 때문에 멤버 변수는 `value`만 가지고 있어도 충분하고,
(변수명도 의미있는 이름으로 변경해 주면 좋겠어요)
메소드도 이 상태를 변경하거나 반환하는 정도만 있어도 되지 않을까 하는 생각입니다.

`distance` 멤버변수는 출력에서 담당해야할 역할이예요.
만약에 출력 방식을 `-`에서 `+`로 변경한다고 하면 도메인 코드를 수정해야하고
이건 관련된 모든 도메인을 다시 테스트해야 한다는 의미입니다.
비용(시간 + 노력)이 엄청나게 들게 되겠죠?😂

참고로 보통 입출력 관련 코드는 테스트에서 제외하곤 해요.
우리 과정 요구사항에서도 입출력 테스트는 안해도 된다고 하고 있고요😄

2021-07-05 23:29 UTC, gw-study commented on src/main/java/Position.java
>      public void setIntegerDistance() {
메소드명도 `increaseDistance` 정도로 변경하면 의미가 명확할거 같아요

2021-07-05 23:29 UTC, gw-study commented on src/main/java/Competition.java
> +        ResultView resultView = new ResultView(competition.history);
```suggestion
        ResultView resultView = new ResultView(competition.history());
```
내부 상태/구현을 숨길수록(캡슐화) 유연하고 결합도가 낮은 코드로 만들수 있어요 :)

2021-07-05 23:29 UTC, gw-study commented on src/main/java/Round.java
> -public class Round {
좋은 설계 였는데 아쉽게 삭제가 되었네요😭

2021-07-13 02:20 UTC, pkh11 commented
리뷰요청드립니다😀

2021-07-14 12:13 UTC, gw-study approved these changes
모든 피드백 적용해 주셔서 감사해요👍

코드 가독성이 굉장히 좋아지고
각 역할들을 심플하게 잘 나누어 주셨습니다. 많이 고민하신거 같아요👏👏👏

특별히 코멘트 드릴게 없어서 이번단계는 여기서 머지 하도록 하겠습니다.

다음 단계는 리팩토링 단계인데요,
패키지를 분리해 보시고
코드를 다시한번 점검해 보면서 리팩토링이 가능한 부분은 없는지,
있다면 어떻게 리팩토링이 가능한지 고민해 보는 단계입니다😁

그동안 학습 하신걸 다시한번 떠올려 보시면 좋을거 같습니다.

그럼 다음 단계에서 기다리겠습니다🚀

2021-07-14 12:13 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +    public List<Car> getWinners() {
스트림 이용 잘해주셨어요!👍

2021-07-14 12:13 UTC, gw-study commented on src/main/java/Position.java
>  public class Position {
`Position`클래스가 한결 깔끔하고 심플해졌습니다👍

2021-07-14 12:13 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
> +                .collect(Collectors.toList());
`distinct`를 사용해서 중복을 제거해 주셨군요!😃

2021-07-14 12:13 UTC, gw-study commented on src/main/java/RacingCarCompetition.java
>      }
생성자 이용 잘해주셨습니다👏👏👏

2021-07-14 12:13 UTC, merged