Step4 리뷰 요청 드립니다.
gw-study/java-racingcar pull request #21
Opened 2021-06-30 23:03 UTC by dahyunja

4단계 - 자동차 경주(우승자)

2021-07-01 06:31 UTC, gw-study requested changes
안녕하세요😃
이번 단계 구현 잘해주셨습니다👏👏👏

코드가 한결 간결해지고 구조가 좋아진거 같습니다👍

코드 전반적으로 고민해보면 좋을 포인트를 아래 몇가지 적어드려요.

- 접근지정자 사용 고민
접근지정자는 그 성격에 맞춰서 사용해 주셔야 합니다.
작성하신 코드를 보면 전체적으로 `public`위주로 사용하신 거 같아요.
`public`접근 지정자는 외부에서 이 메소드를 사용해도 괜찮다는 의미입니다.
반대로 말하면 내부에서만 사용하는 메소드의 경우는 `public`일 필요가 없는거죠
사실 `public`으로 정의된 메소드는 모두 테스트 코드를 만들어야 하는 대상이예요😱
`private`로 선언할 메소드는 없는지 고민 부탁드려요

- 포맷팅 체크
코드 포맷팅을 많이 준수해 주셨지만 특정 부분(예: `int i=0`)에 포맷팅이 적용되지 않은 것이 종종 보입니다.
전반적으로 체크 부탁드려요. (`Save Actions`를 세팅하면 자동으로 포맷팅해줍니다)

- Winner클래스 생성은 어떨까요?
`RacingCar`클래스의 `findWinner`가 우승 자동차를 가져오는 역할인 거 같습니다.
이 역할을 Winner(명칭은 꼭 이게 아니여도 됩니다)클래스를 생성하여 역할을 위힘해 보길 추천드려요😁

- 점`.`은 하나만 사용
코드 전반적으로 점`.`을 두개 이상 사용하신 곳이 보입니다.
아래 링크를 확인해 보시고 점`.`을 줄일 수 있는지 고민 부탁드릴께요🙏
[규칙 4: 한 줄에 점을 하나만 찍는다](https://7942yongdae.tistory.com/29)

그 외 코멘트 드린 내용이 있으니 확인 해보시고 다시 한번 리뷰 요청 부탁드릴께요🙇‍♂️

2021-07-01 06:31 UTC, gw-study commented on README.md
> +* 자동차 경주 게임의 우승자를 출력하는 기능
기능목록 정리 잘해주셨어요👏

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    private final int MOVE_CONDITION = 4;
매직넘버를 상수로 변환👍
근데 상수라면 `static` 키워드 추가 부탁드려요
그리고 상수는 맨 처음 부분에 선언해 주는게 일반적입니다.😁

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    private ArrayList<String> winner;
인스턴스변수가 너무나 많아요!
대체적으로 한 클래스에 3개이상의 인스턴스 변수는 사용하지 않도록 가이드하고 있습니다.
만약에 3개이상의 클래스를 써야한다면 그건 리팩터링을 통해 클래스를 분리해야할 여지가 있다는 얘기일지 몰라요🤔
지금 케이스는 필요없는 멤버변수는 없는지 고민해 볼 수 있을거 같아요😃
메소드로 변경해도 충분할 내용이 보이는 것 같습니다

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCarMain.java
>          for (int i=0; i < racingCar.getCountOfRounds(); i++){
```suggestion
        for (int i = 0; i < racingCar.getCountOfRounds(); i++) {
```
코드 포맷팅 적용 부탁드릴께요🙏

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        for (int i=0; i < countOfCars; i++){
```suggestion
        for (int i = 0; i < countOfCars; i++) {
```
코드 포맷팅 체크!

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    }
이 메소드를 테스트 해볼 수 있을까요?🤔
힌트 : 테스트하기 힘든 메소드와 테스트가 가능한 메소드를 분리

2021-07-01 06:31 UTC, gw-study commented on src/test/java/racingcar/step3/RacingCarTest.java
> +    void findWinner() {
테스트가 의도하는 목적과 구현한 코드의 의미가 맞지 않은거 같습니다🤔
자동차 경주를 N회 진행 했을때 우승 자동차 이름을 테스트하도록 변경해 볼 수 있을까요?
```java
자동차 = A,B,C 3대
시도횟수 = 2회 라고 하면,

//1회
a.move(1); //1칸
b.move(2); //1칸
c.move(8); //0칸

//2회
a.move(1); //2칸
b.move(5); //1칸
c.move(6); //0칸

assertThat(winner.findWinnerNames()).isEqualTo("a");
```
이런식으로 말이죠😁

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        for (int i=0; i < countOfCars; i++){
포맷팅 체크!

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        for (int i=0; i < countOfCars; i++) {
포맷팅 체크!

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        if(infoOfCars.get(i).getPositionOfCar() == max){
포맷팅 체크!

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        }
```suggestion
        for (String carName : namesOfCar) {
            infoOfCars.add(new Car(carName, 0));
        }
```
이렇게 변경하면 조금더 심플한거 같아요😁

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    public void addWinner(int max, int i){
클래스 외부에서 호출되지 않는 메소드는 `private`로 선언해주세요🙏

2021-07-01 06:31 UTC, gw-study commented on src/main/java/racingcar/step3/Car.java
> +public class Car {
Car객체 생성 잘 해주셨네요👍

2021-07-05 15:55 UTC, dahyunja commented
피드백 적용 리뷰 요청 드립니다.

2021-07-06 06:54 UTC, gw-study approved these changes
피드백 적용하시기 힘드셨을텐데 모두 적용해 주셔서 감사해요👍

이전에 비해 코드가 역할 분리가 잘 되어 있고
접근자 및 포맷팅 규약도 잘 지켜주셨어요!

그래서 코드가 한결 읽기 수월했답니다😁

소소한 코멘트 몇가지 남겨드렸는데 다음 단계 진행하시면서 고민해 보셨으면 합니다

이번 단계는 여기서 머지하도록 할께요

다음 단계는 리팩터링 단계인데요 패키지 분리와 함께
코드 전반적으로 리팩터링 할 내용이 있는지 다시 고민해봐 주세요 :)

그럼 다음 단계에서 만나겠습니다🚀

2021-07-06 06:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +    private ArrayList<Car> infoOfCars;
리스트의 타입 매개변수 정의 잘 해주셨어요.👍
Effective Java라는 책에 보면 이런 내용이 있어요.
[아이템26. 로 타입은 사용하지 말라](https://madplay.github.io/post/dont-use-raw-types)

이걸 잘 지켜주셨습니다👏

2021-07-06 06:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +        String[] namesOfCar = nameOfCars.split(",");
콤마`,`로 분리해서 배열로 만드는 행위도 사실 View의 역할인거 같습니다.😄

2021-07-06 06:54 UTC, gw-study commented on src/main/java/racingcar/step3/RacingCar.java
> +            racingCar.move(i, RandomNumber.makeRandomNumber());
```suggestion
            move(i, RandomNumber.makeRandomNumber());
```
요렇게 사용하는건 안될까요?
인자로 나(Self)를 받아서 내 함수를 호출해야 할 이유가 있는지 궁금합니다🤔

2021-07-06 06:54 UTC, gw-study commented on src/main/java/racingcar/step3/Winner.java
> +public class Winner {
`Winner`클래스 잘 만들어 주셨어요!👏👏👏

2021-07-07 10:06 UTC, merged