Step4 리뷰 요청 드립니다
gw-study/java-racingcar pull request #22
Opened 2021-07-05 00:11 UTC by a-ri-mu

안녕하세요 차장님
STEP 4 리뷰 요청 드립니다.

2021-07-05 07:55 UTC, gw-study requested changes
저번단계 피드백 드린 내용을 모두 잘 적용해 주셨어요

커밋도 잘 나눠주시고 코드도 한결 정리되고 깔끔해져서 리뷰하는데 수월했습니다

특별하게 요청드릴 내용은 없지만
도메인과 출력 역할의 분리,
코드 중간중간에 보이는 소소한 부분들에 대해 코멘트를 몇개 드렸습니다.

확인해봐 주시고 다시 한번만 Request Change 하겠습니다.
궁금하신거 있으시면 언제든지 DM주세요.

리뷰요청 기다리겠습니다🙇‍♂️
화이팅!🔥🔥🔥

2021-07-05 07:55 UTC, gw-study commented on README.md
> +
기능목록 작성👍

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/RacingCar.java
>          }
```suggestion
        for (String car : carNameList) {
            carList.add(new Car(car));
        }
```
이렇게 하면 조금더 간결하고 보기 좋겠네요😃

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/RacingCar.java
> +    public boolean racing() {
시도횟수를 함수로 분리 잘해주셨어요👏

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/Car.java
>      private String curPosition = "";
`curPosition`을 문자열이 아닌 int로 가지고 있는건 어떨까요?
지금 형태는 "출력 형태를 `+`로 바꿔주세요!" 라는 요청 사항이 발생하면
도메인 코드를 수정해야 할 것 같습니다😂
그럼 테스트도 다시 해야하고 일이 많이 발생할 수 있겠죠?😄

위치정보에 대한 상태값만 가지고 있고 출력은 출력 클래스에서 알아서 할 수 있도록 인자로 던져주는거죠
(보통 입출력은 테스트에서 제외하곤 합니다)

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/WinnerCars.java
> +    private final int MAX_POSITION;
`MAX_POSITION` 이 변수명은 상수에대한 명명법이예요😭
일반적인 변수명명법으로 변경부탁드립니다🙏

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/WinnerCars.java
> +            maxPosition = Math.max(maxPosition, car.getCurPosition().length());
API를 잘 이용해서 최대값을 잘 찾아주셨어요👏👏👏

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/WinnerCars.java
> +        if (car.getCurPosition().length() == MAX_POSITION) {
`Car`객체의 위치 멤버변수(`curPosition`)가 int값을 가지도록 변경하면 점`.`은 하나만 있어도 될거같네요 :)

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/RandomMovingStrategy.java
> +public class RandomMovingStrategy implements MoveStrategy {
구현 잘해주셨습니다👍👍👍

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/RandomMovingStrategy.java
> +        return false;
```suggestion
        return getRandomNumber() >= MOVABLE_NUM;
```
이렇게 하면 코드량도 줄어들고 심플해질거 같은데요?😄

2021-07-05 07:55 UTC, gw-study commented on src/main/java/RacingCar/ResultView.java
> +    ResultView() {
접근제한자를 붙이지 않으면 `default`(`package-private`) 접근으로 인식합니다.
이걸 의도하고 접근제한자를 명시하지 않으신걸까요?🤔

2021-07-05 07:55 UTC, gw-study commented on src/test/java/CarTest.java
> +    public void winnerTest() {
테스트 수행 잘해주셨어요!👍👏
인터페이스를 이용한 코드의 장점과 유연성을 경험할 수 있는 기회가 되었는지 모르겠네요😄

2021-07-07 10:53 UTC, a-ri-mu commented
차장님 피드백 적용 완료했습니다.

감사합니다:)

2021-07-08 00:21 UTC, gw-study approved these changes
안녕하세요!😃
피드백 빠르게 모두다 적용해 주셨네요👍

코드가 상당히 깔끔하고 간결해졌어요!!!
읽는데 막힘없이 수월하게 읽을 수 있었습니다👏👏👏

다만 테스트가 실패하는 부분이 있는데요,
아마 깜박하고 놓치신거 같아요.
이 부분 포함해서 몇개 코멘트를 남겨 놓았는데요 다음 단계에서 적용해봐 주시면 되겠습니다

이번 단계는 여기서 머지하도록 할께요
다음 단계는 리팩토링 단계인데 패키지 분리를 해주셔야 할거예요
요구사항 외에도 혹시 자기 코드에 리팩토링이 필요하다 싶은 부분은 리팩토링을 해주시면 됩니다 😊

다음 단계에서 만날께요🚀

2021-07-08 00:21 UTC, gw-study commented on src/main/java/RacingCar/ResultView.java
> +    private final String displayPosition = "-";
도메인과 출력 분리 피드백 적용 잘해주셨어요!👍
이왕이면 `private static final String DISPLAY_POSITION = "-";` 요렇게 상수로 선언하는게 더 좋을거 같습니다!😁
요 문자는 한번 정의하면 바뀔일이 없으니까요

2021-07-08 00:21 UTC, gw-study commented on src/main/java/RacingCar/Car.java
> +    private int curPosition = 0;
피드백 적용 잘해주셨어요👏

2021-07-08 00:21 UTC, gw-study commented on src/main/java/RacingCar/ResultView.java
> +        StringBuilder result = new StringBuilder("");
```suggestion
        StringBuilder result = new StringBuilder();
```
이렇게 해주는게 좋겠죠? :)

2021-07-08 00:21 UTC, gw-study commented on src/test/java/CarTest.java
>  class CarTest {
요 두개의 테스트가 실패를 하고 있네요😭
![image](https://user-images.githubusercontent.com/84048349/124843227-712c8e80-dfcc-11eb-8c1e-f95c46613e27.png)

테스트 코드를 작성했을 때 이점은 
코드를 수정하고 난 다음에 테스트를 돌려봤을때
성공여부를 확인하여 코드와 테스트 코드의 이상 유무를 손쉽게 확인할 수 있는 점 같아요
그렇기 때문에 코드 수정에 대한 두려움이 적어질 수 있지요 :)

코드 수정후에 항상!꼭!! 테스트 코드도 실행하는 습관을 가져주세요😊

2021-07-08 00:21 UTC, merged