Step5 리뷰 요청드립니다
gw-study/java-racingcar pull request #23
Opened 2021-07-13 00:10 UTC by a-ri-mu

차장님 안녕하세요:) 

4단계 피드백 적용 및 step5 과제 완료했습니다. 

혹시 리팩토링을 더 할 수 있는 부분이 있을까요? 

피드백 부탁드립니다. 감사합니다:)

2021-07-13 11:59 UTC, gw-study requested changes
마지막 리팩터링 단계 잘 진행해주셨습니다👏

이번 단계 주요내용은 패키지 분리와 테스트 진행이 가능한 로직의 분리였는데요,
이전 단계에서 해당 내용을 잘 구현해 주셔서 특별하게 코멘트를 드릴 부분은 없습니다.😄

제가 아래에 드리는 내용은 보너스 문제 정도라고 생각하시고
한번 도전해 볼 생각이 드시면 도전해봐 주세요😎

1. 현재 정수형으로 선언되어 있는 시도횟수(`tryCnt`)변수를 하나의 객체로 분리해 볼 수 있을까요?
객체로 분리를 한다면 시도횟수 상태와, 시도횟수와 관련된 행동(시도횟수를 하나씩 줄이고 시도횟수가 남아있는지 여부)들을 이 객체에서 할 수 있을거 같습니다.
2. 자동차 경주 결과를 따로 관리하는 객체를 생성해 보는건 어떨까요?
3. 2를 만들었다면 ResultView의 생성자로 2를 받아서 출력해 볼 수 있을까요?

이 정도로 생각해 볼 수 있는 거리를 좀 드릴께요😁

여기에서 과정을 마칠수도 있지만 한번더 생각해보시라고 Request Change하겠습니다.
그럼 다음 리뷰요청에서 만나요~😃

2021-07-13 11:59 UTC, gw-study commented on src/main/java/RacingCar/Main.java
> +import RacingCar.view.ResultView;
패키지 분리 잘해주셨어요👍

2021-07-13 11:59 UTC, gw-study commented on src/main/java/RacingCar/Main.java
>  package RacingCar;
패키지 명명규칙 중에 하나는 대문자 사용금지 입니다😭
`RacingCar` -> `racingcar`또는`racing-car`정도로 변경할 수 있을거 같아요

2021-07-15 09:40 UTC, a-ri-mu commented
차장님 안녕하세요 

주신 피드백 내용을 토대로 리팩토링 및 테스트 케이스를 추가하였습니다.

피드백 부탁드립니다:)

2021-07-17 06:19 UTC, gw-study approved these changes
리뷰요청이 온걸 늦게 깨달았어요!😂
피드백이 늦어서 죄송해요~🙏

제가 저번단계에 드린 모든 피드백을 적용해 주셔서 감사해요👍💯
(패키지 명명규칙 관련건은 아직 미적용이지만 이건 나중에 적용해도 될거 같습니다😁)

각 클래스의 역할이 조금더 명확해지는 느낌을 얻을 수 있었으면 좋겠습니다.
새롭게 추가된 클래스의 테스트 케이스도 꼼꼼하게 잘 적용해 주셨고
전반적으로 큰 이견이 없어서 이번 단계는 여기서 머지 하도록 하겠습니다.

몇개 코멘트 드린 내용은 확인해 보시고 나중에 과정이나 코딩하실때 생각해봐 주심
좋을거 같아요😀

드디어!!자동차 경주 과정이 끝났습니다.👏👏👏
길다면 긴 시간이였는데 끝까지 과정 진행하느라 너무 수고하셨어요.

처음 리뷰요청때 코드랑 지금 코드랑 비교해 보면
많은게 달라졌다고 느낄 수 있을거예요.
적어도 저는 그렇게 느끼고 있습니다 😀

다음 과정은 로또인데요 저는 다시 로또 과정에서 기다리고 있을께요😁
좋은 주말 보내세요~

2021-07-17 06:19 UTC, gw-study commented on src/main/java/RacingCar/domain/TryCnt.java
> +public class TryCnt {
시도횟수 클래스로 분리 잘해주셨습니다👍

2021-07-17 06:19 UTC, gw-study commented on src/main/java/RacingCar/domain/TryCnt.java
> +        }
생성자에서 초기화하는 멤버변수를 검증하게 되면 객체의 상태값(=멤버변수)을 보증할 수 있는 장점이 있습니다.
값 체크로직 Good👏

다만 한가지 말씀드릴게 있다면,
검증 로직이 먼저 실행되게 두어서 검증이 통과한 값만 변수에 할당하는게
논리적으로나 시스템 효율적으로나 더 좋을거 같습니다😁

2021-07-17 06:19 UTC, gw-study commented on src/main/java/RacingCar/domain/TryCnt.java
> +    public boolean checkTryCnt() {
시도횟수가 남아있는지 여부를 반환하는 메소드 사용 좋습니다!

하나 더 나아간다면, 
지금 시도횟수를 하나씩 줄여주고 있는 행동과
시도횟수가 남아있는지 여부를 판단하는 행동 두가지를 하고 있는데요
이건 각각의 메소드로 나눠주는게 좋을거 같단 생각이예요.
예를들면 `decreaseTryCnt`와 `isEndedTry` 뭐 이런식으로 메소드명을 지을수 있을거 같아요

2021-07-17 06:19 UTC, gw-study commented on src/main/java/RacingCar/domain/RacingResultCars.java
> +public class RacingResultCars {
경주결과 클래스 설계 Good👍

2021-07-17 06:19 UTC, merged