Step2 - 2단계 리뷰 요청드립니다
gw-study/java-racingcar pull request #8
Opened 2021-06-04 03:46 UTC by a-ri-mu

base : master 로 잘못 지정하여 재지정해서 리뷰 요청드립니다.

2021-06-04 07:04 UTC, gw-study requested changes
리뷰요청을 굉장히 빠르게 해주셨네요 :)
전체적으로 코드가 깔끔하고 역할 분담이 잘 되어 있어서 리뷰하기에 수월했습니다.

코멘트에도 남겨놓았지만 이번단계는 프로덕션 코드를 만들고
프로덕션 코드에 대한 테스트 코드를 작성하는 학습을 해볼거에요.
두 역할에 대해 분리 부탁드릴께요🙇‍♂️

그 밖에 몇개 코멘트 남겨 놓았으니 확인해주시고 다시 리뷰 요청 부탁드립니다.🙏
궁금한 내용이나 잘 안되는게 있으면 PR 본문에 댓글로 남겨주셔도 되구요,
슬랙DM날려 주시면 확인하고 회신드릴께요😃

2021-06-04 07:04 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +    @ValueSource(strings = {"", "  "})
Null체크를 위해서 NullAndEmptySource 사용하셨네요👍
다만 두개 같이 선언하시는건 중복입니다. 둘 중 하나만 사용하셔도 무방합니다😀

2021-06-04 07:04 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +    private int addition(int a, int b){
사칙연산에 대해 메서드 분리 아주 잘해주셨어요.👍

이번 단계는 프로덕션 코드와 테스트 코드를 분리해 보기를 부탁드릴께요.
`Calculator`와 같은 프로덕션 코드를 만들고
`CalculatorTest`는 프로덕션 코드를 테스트하는 역할만 수행하는 거죠😄

2021-06-04 07:04 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +    @ParameterizedTest
`@ParameterizedTest`의 name 속성을 사용해서 테스트별 디스플레이네임을 커스터마이징 해볼 수 있을까요?

2021-06-04 07:04 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +        }).withMessageMatching("input data is blank or null");
저도 처음에는 예외처리 테스트를 코딩하신 것처럼 했었는데요,
아래 처럼 하는게 훨씬 가독성도 좋고 일반적이라고 하더라구요.
이건 개인적인 생각입니다.😁
```suggestion
        assertThatThrownBy(() -> calculator(input))
                .isInstanceOf(IllegalArgumentException.class);
```

2021-06-04 07:04 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +    private int calculator(String input){
이번 단계의 핵심로직 아주 잘 작성해 주셨어요✔

아래 내용을 고민해본다면 더욱 좋은 코드가 나올거 같습니다.😅
- `value, Integer.parseInt(inputArr[i + 1]`과 같은 로직이 계속 반복되고 있네요. 
반복을 줄일 수 있는 방법은 어떤게 있을까요?
힌트 : enum을 사용하면 다형성을 구현할 수 있습니다. (enum 에도 스테틱이 아닌 맴버 필드와 메소드를 정의할 수 있어요.)
- switch 문도 if/else 와 같은 의미입니다. switch문 사용은 자제해 주세요.

2021-06-08 04:33 UTC, gw-study requested changes
피드백 적용 잘해주셨어요👍👍👍
`enum`사용도 적절하게 잘 해주셨고 변수명이나 함수 생성도
깔끔하게 잘 작성해주셨습니다.😄

여기서 머지할수도 있는데
한번 더 생각해볼 여지가 있어서 코멘트 몇개 남겨놓아요.

확인해보시고 한번더 리뷰 요청 주세요🙏
다음 요청엔 머지가능할 거 같습니다!
그럼 퐈이팅~🔥

2021-06-08 04:33 UTC, gw-study commented on src/main/java/Calculator.java
> +import jdk.nashorn.internal.runtime.regexp.joni.constants.OPCode;
사용하지 않는 코드는 삭제해주세요🙏

2021-06-08 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +import org.junit.jupiter.params.provider.NullAndEmptySource;
사용하지 않는 코드는 삭제해주세요🙏

2021-06-08 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +import static org.junit.platform.commons.util.StringUtils.isBlank;
사용하지 않는 코드는 삭제해주세요🙏

reformat 을 자주 놓친다 생각되시면 자동화 해 볼 수 있습니다. 
인텔리제이를 사용하신 다면 `Save Actions`을 검색해보시고 사용해보세요.👍

2021-06-08 04:33 UTC, gw-study commented on src/test/java/CalculatorTest.java
> +        assertEquals(10,calculator.calculate(input));
```suggestion
        assertEquals(10,calculator.calculate( "2 + 3 * 4 / 2"));
```
불필요한 로컬변수는 inline 하면 가독성이 좋아져요.
로컬변수가 존재하면 컴퓨터는 메모리에 저장하고 사람은 기억해야 하는데 사람의 경우엔 임시로 기억해야하는 대상이 많아질수록 기독성이 떨어진다고 느끼거든요.

그리고 `assertEquals`를 사용하신 다른 이유가 있는지요?🤔
`assertThat`으로도 충분히 테스트가 가능해 보입니다.

2021-06-08 04:33 UTC, gw-study commented on src/main/java/Calculator.java
> +    public enum OperationType{
enum을 이용한 사칙연산 아주 잘 구현해주셨습니다👍

2021-06-08 04:33 UTC, gw-study commented on src/main/java/Calculator.java
> +    private static Map<String, OperationType> operators = new HashMap<>();
사칙연산을 Key로 설계 했군요!아주 잘하셨어요!👍👏✔

음..근데 제 생각을 조금 말씀드리면요,
위에 enum으로 사칙연산과 행동을 정의해 놓고,
이 enum을 다시 Map의 키와 값으로 세팅하는건 중복된 코드 같아 보입니다.
enum 또는 Map 한가지로만 구현하는게 어떨까 생각되는데 어떨까요?😄

2021-06-11 03:28 UTC, a-ri-mu commented
차장님 안녕하세요:) 

피드백 내용 수정 완료하여 리뷰 요청드립니다. 

1. IntelliJ에서 Save Actions 설정을 추가해 reformat 자동화
2. assertEquals -> assertThat , 로컬변수 inline 
3. Map 으로 구현하였습니다 (enum 삭제)

2021-06-11 07:57 UTC, gw-study commented on src/main/java/Calculator.java
> +    private static final Map<String, BiFunction<Integer, Integer, Integer>> operators = new HashMap<>();
Map을 이용한 사칙연산 설계 아주 멋집니다👍👍👍

2021-06-11 08:05 UTC, gw-study approved these changes
피드백 적용 감사해요😄

포맷팅은 팀 또는 다른 동료와의 일종의 약속이라고 생각해요.
포맷팅을 적용해 주셔서 코드가 한결 가독성이 좋아지고
리뷰를 진행하는데도 편해졌습니다.👍👍👍

Map을 이용한 문자열 계산기가 아주 훌륭하네요👏

이번 단계는 여기서 머지 하도록 할께요.
다음 단계는 이번 미션의 메인 구현 단계입니다.  지금까지 학습한 내용을 참고해서 구현해봐주세요~😄
그럼 다음 PR기다리고 있겠습니다🙇‍♂️

2021-06-11 08:05 UTC, merged