TEST: step2 문자열계산기 테스트코드 작성
gw-study/java-racingcar pull request #9
Opened 2021-06-04 08:34 UTC by pkh11

step2 리뷰 요청 드립니다.

2021-06-04 13:16 UTC, gw-study requested changes
두번째 step 구현 잘하셨습니다.👍

이번 단계는 단위테스트 코드를 작성하는 방법을 배우고 있는데요,
프로덕션 코드와 테스트 코드를 잘 분리해주셨습니다✔

이번단계에서 가장 핵심적인 테스트는 주어진 문자열에 대해
정확한 계산값을 리턴하느냐 인거 같습니다.
이걸 구체적으로 말씀드리면 `1+2*4/6`에 대한 결과값은 `2`와 같은 결과값을
기대할수 있도록 테스트 코드가 작성이 되어야 할거 같아요
이런 테스트 코드가 누락이 되어있는거 같아서 추가 부탁드리겠습니다.🙏

그리고 `calculate` 메소드 안에 사칙연산별 if문이 들어가 있는데요,
이걸 아래 힌트를 참고해서 변경해보시길 바라겠습니다.
- 힌트 : enum을 사용하면 다형성을 구현할 수 있어요. 다형성을 구현하면 if문을 사용하지 않을 수 있습니다. (enum 에도 스테틱이 아닌 맴버 필드와 메소드를 정의할 수 있어요.)

진행하면서 막히는 부분이 있거나 궁금한 내용이 있으면 언제든지 DM날려주셔도 됩니다.😄

그럼 재리뷰 요청 기다릴께요.
주말 잘 보내세요~🔥😄

2021-06-04 13:16 UTC, gw-study commented on src/main/java/Main.java
> +public class Main {
Main클래스의 역할은 어떤걸까요?🤔
혹시 필요하지 않은 클래스라면 삭제를 부탁드릴께요 :)

2021-06-04 13:16 UTC, gw-study commented on src/main/java/StringCalculator.java
> +    public String calculate(String str1, String operator, String str2) throws IllegalArgumentException {
`String str1` `String str2` : 문자열을 파라메터로 받은 이유가 있을까요? calculate라는 메소드는 문자보다는 숫자를 파라메터로 받는게 명확한 표현이지 않을까 생각합니다.
마찬가지로 리턴 타입도 String 보다는 실수형이 알맞지 않을까 생각됩니다.🤔

2021-06-04 13:16 UTC, gw-study commented on src/main/java/StringCalculator.java
> +            return toString(result);
숫자형을 리턴하는 메소드가 된다면 형변환을 하지 않아도 될거 같아요😄

2021-06-04 13:16 UTC, gw-study commented on src/main/java/StringCalculator.java
> +            return toString(result);
early return 패턴 사용 잘하셨어요👍
if문 안에서 리턴을 하면 코드가 좀더 명확해지고 else문을 사용하지 않을 수 있는 효과를 얻을 수 있습니다.

2021-06-04 13:16 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +        ).withMessage("Input IllegalArgument Exception");
예외처리 테스트 코드 작성 잘하셨습니다.✔
저도 처음에 이런 방식으로 코드를 작성했는데요
아래처럼 작성하는게 좀더 명확해보이고 일반적이라고 하네요. 참고해보세요😃
```suggestion
        assertThatThrownBy(() -> calculator.enterCommand(input))
                .isInstanceOf(IllegalArgumentException.class);
```

2021-06-04 13:16 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +    @ParameterizedTest
`@ParameterizedTest`의 name 속성을 사용해서 테스트별 디스플레이네임을 커스터마이징 해볼 수 있을까요?

2021-06-04 13:16 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +        int result = calculator.add(5,3);
테스트로 주어지는 값은 `String given = "5 + 3"`과 같이 문자열 형식이어야
요구조건을 만족할 수 있을거 같아요😭

2021-06-04 13:16 UTC, gw-study commented on src/main/java/StringCalculator.java
> +        return inputs;
```suggestion
        return  input.split(" ");
```
이런 형식으로 변경할 수 있을거 같아요.
로컬 변수를 사용하면 사람은 `이 변수가 무슨 의미였더라?`라고 한번 더 생각하는
시간이 필요하게 되어서 코드 읽기에 시간이 조금 더 필요하게 된답니다.😄
(물론 로컬 변수가 필요한 경우도 있어요🤣)

2021-06-04 13:16 UTC, gw-study commented on src/test/java/SetTest.java
> -import static org.junit.jupiter.api.Assertions.*;
피드백 적용 잘해주셨네요👍

2021-06-08 01:01 UTC, pkh11 commented
리뷰 요청드립니다!
추가로, 커밋메세지 규칙에 대해서 찾아보고 나름 규칙에 맞게 작성했는데.. 같이 리뷰 부탁드려도 될까요?

2021-06-08 23:34 UTC, gw-study requested changes
리뷰가 늦어서 죄송해요.
제가 리뷰요청을 늦게 확인했네요😭

각 연산자별 행동을 enum과 인터페이스를 사용하여 정의한 것, 아주 인상깊었어요.👍👍👍
테스트 케이스도 꼼꼼하게 잘 작성해주셨고
코드도 간결하고 역할분리도 잘 해주셨습니다.👏

몇가지 수정하면 좋을 부분이 있어서 Request change 할께요.
피드백 확인하시고 리뷰 요청 다시 부탁드리겠습니다.🙇‍♂️

앗!커밋 메세지도 보기 편하게 잘해주셨어요.
다음 스텝에 commit conversation 관련 내용이 나올거지만 앞으로 이렇게 해주시면
리뷰하는데 상당히 편해질거 같아요.👍

오늘도 수고하세요 :)

2021-06-08 23:34 UTC, gw-study commented on src/main/java/Operation.java
> +public enum Operation implements Calculation {
사칙연산별 행동을 enum과 인터페이스를 이용해서 훌륭하게 잘 구현해주셨어요👍👍👍

`BiFunction` 이란 걸 이용하면 아래처럼 작성할 수도 있습니다.
`ADDITION("+", (number1, number2) -> number1 + number2)`
결국 지금 코드랑 의미는 동일한데요 코드량이 조금더 줄어들고
간결해 질 수 있는 장점이 있는거 같아요😄
이건 참고만 해주세요~ :)

2021-06-08 23:34 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +        }
반복되는 행동을 잘 찾아주셨어요👏

그런데 이 로직은 이번 스텝의 핵심 비지니스 로직이라고 할 수 있어요
테스트 코드에 있는 것 보다는 프로덕션 코드에 위치하는게 적절할 거 같습니다.
프로덕션 코드로 이동 부탁드려요🙏

2021-06-08 23:34 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +    }
```suggestion
    void addTest(){
        assertThat(calculator.calculation("5 + 3")).isEqualTo(8);
    }
```
이런방식으로 테스트가 가능하도록 바꿔볼 수 있을까요?

사실 문자열을 자르고 자른 문자열을 인수로 전달하고 하는 행위들은
이 API를 사용하는 사람들은 중요하게 생각하지 않을거 같아요.
(혹시나 이 서비스를 API로 제공할 수도 있다고 생각해 보면요😄)
`5 + 3`의 결과가 `8`로 잘 나오는게 제일 중요하지 않을까 생각됩니다

2021-06-08 23:34 UTC, gw-study commented on src/test/java/StringCalculatorTest.java
> +        float result = calculator.calculation(num1, Operation.MINUS, num2);
`calculator.calculation`의 리턴값은 `int`이지만 `float`로 결과를 받고 있습니다.
특별한 이유가 없다면 `int`로 받는게 좋다는 의견입니다😄

2021-06-09 08:24 UTC, pkh11 commented
리뷰 감사합니다😃 

피드백 주신대로 아래와 같이 수정하여 다시 리뷰 요청드립니다.
1) 프로덕션 코드와 테스트 코드 분리
 하다보니, 프로덕션코드만 잘 짜두면 테스트 코드는 프로덕션코드에 있는 함수나 로직만 가져다 쓰면 돼서 편한거 같아요.
2) calculation 함수 인자를 String형태로 받아서 처리 할 수 있도록 변경


한가지 질문있습니다. 

코드 작성하다보면 
assertThat(calculator.calculation("5 + 3")).isEqualTo(8) 와 같이 간단한 테스트 구현 코드인데
calculator.calculation("5 + 3") 이 부분을 따로 변수로 빼서 코드를 작성하는 방법이 올바른? 클린한? 코드인지가 궁금합니다.


예를 들면, 아래 코드와 같이 입니다. 

```java
int result = calculator.calculation("5 + 3"); 
assertThat(result).isEqualTo(8);
```

변수로 따로 빼는 것이 다른사람이 봤을때, 무슨 역할을 하는지 한눈에 볼 수 있어서 주로 사용하는 편입니다.

2021-06-09 22:36 UTC, gw-study commented on src/main/java/StringCalculator.java
> +    public int setInputs(String inputs) {
피드백 적용 잘해주셨습니다👍

2021-06-09 22:37 UTC, gw-study approved these changes
피드백 적용 잘해주셨습니다👏👏👏

로컬 변수 사용관련하여 질문을 주셨네요~👍
> 코드 작성하다보면
assertThat(calculator.calculation("5 + 3")).isEqualTo(8) 와 같이 간단한 테스트 구현 코드인데
calculator.calculation("5 + 3") 이 부분을 따로 변수로 빼서 코드를 작성하는 방법이 올바른? 클린한? 코드인지가 궁금합니다.

제가 피드백 받았던 내용을 보내드릴께요 :)
> 불필요한 로컬변수는 inline 하면 가독성이 좋아져요.
로컬변수가 존재하면 컴퓨터는 메모리에 저장하고 사람은 기억해야 하는데 사람의 경우엔 임시로 기억해야하는 대상이 많아질수록 기독성이 떨어진다고 느끼거든요.

이 피드백을 받고 저도 생각을 많이 했었는데요,
로컬 변수를 inline으로 사용하는게 오히려 가독성이 더 좋다는 결론이였습니다.
그리고 변수(variable, 變數)라는 말 자체가 가지고 있는 정의를 생각해 보면
의외로 로컬변수를 사용하지 않아도 될 곳이 많이 보이는 거 같더라구요

사실 이에 대한 정답은 없기 때문에(클린코드에도 소개된 내용은 아닙니다)
자신만의 기준을 갖고 상황에 따라 사용하는게 중요한거 같아요.😄

이번 단계는 여기서 머지하도록 하겠습니다.
다음단계는 이번 미션의 메인이예요.
지금까지 학습한 단위테스트 방법을 잘 적용해서 구현해 보세요.
퐈이팅입니다~🔥🔥🔥

2021-06-09 22:38 UTC, merged